### ISSUE TITLE
Should run on port 80

### ISSUE THREAD

**Issue by sirkitree** [sirkitree/cosmos-middleware-neos#1]

**Comment by satanasov** [comment]
Why do you need it on port 80?

I can do a quick docker image and host it my side of town ... using http_proxy.

**Comment by sirkitree** [comment]
I'm anticipating this need for Heroku, but I could be mistaken. I'll know more once I try to get it running there.

**Comment by sirkitree** [comment]
heroku needed a way to use it's own process environment PORT variable, fixed in https://github.com/sirkitree/cosmos-middleware-neos/commit/55f903c54e5475c4281d4acc441de7847d9b7dd8
