### ISSUE TITLE
Account endpoint

### ISSUE THREAD

**Issue by sirkitree** [sirkitree/cosmos-middleware-neos#19]
We should have a way to call in account information when passed an account hash 

Hash examples: 
- cosmos1lsrl2uzphdzuk0lghrfe0d3rg5k2vf0km8svh6
- cosmos1yeygh0y8rfyufdczhzytcl3pehsnxv9d3wsnlg

Endpoint should be:
- `/account/[hash]`

Account info should contain:
- account hash
- balance
  - available
  - delegated
  - unbonding
  - rewards
  - total Atoms
  - USD equivalent based on current conversion rate (eg. ~$15.0000m @ $3.72/Atom)
- Delegations (validator)

This should also return a list of the last 100 transaction hashes so we can see what transactions are associated with an account.

Transaction info should contain:
- tx hash
- tx type [transfer, staking, distribution, governance, slashing]
- amount transferred

**Comment by satanasov** [comment]
Information can be found for:

Account hash
Balance - available and denomination, as well as rewards.

We could probably calculate the USD amount.

Delegations - can probably be found.

But I can't find a way to get info about transactions created by account

**Comment by sirkitree** [comment]
In looking through the big_dipper application, it seems that they are storing transactions in a mongodb in order to do a lookup by address. https://github.com/forbole/big_dipper/blob/master/imports/api/transactions/transactions.js

There is a way that we can get transactions by sender from the SGAPI though: https://sgapiv2.certus.one/v1/transactions?limit=100&sender=cosmos1lktjhnzkpkz3ehrg8psvmwhafg56kfss5597tg

...where `sender` is the an account address.

I think that may be sufficient?

**Comment by satanasov** [comment]
Where do we get the price of an atom? 

Never mind .. :)
