### ISSUE TITLE
Investment data

### ISSUE THREAD

**Issue by sirkitree** [sirkitree/cosmos-middleware-neos#24]
![The Big Dipper _ Cosmos Explorer by Forbole - Google Chrome 2019-08-10 15 52 47](https://user-images.githubusercontent.com/28543/62827646-05470e80-bb88-11e9-942e-12f875b6f156.png)

Create an endpoint that gives us the following data:
- Price
- Market Cap
- Inflation
- Community Pool

This is shown on the big_dipper application at the top at all times and would be a good re-usable component to display in our worlds.

**Comment by satanasov** [comment]
Inflation and community pool are not exposed to the internet. They are taken from https://gaia-seeds.interblock.io:1317 which is not exposed ... and I don't see how can I get it.
